---
  pool: testatorg level

  trigger:
    - master
  
  jobs:
    - job: dotnetbuild
      displayName: dotnet
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: src/dotnet-demoapp.csproj
    - job: testjob
      displayName: dotnettest
      dependsOn: Build_Job
      condition: succeeded()
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: test/tests.csproj